version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
#      - ./compose/postgres/initdb:/docker-entrypoint-initdb.d
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
    env_file:
      - dev.env

    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    container_name: db_migrations
    env_file:
      - ./migrations/.env
    build:
      context: ./migrations
    depends_on:
      db:
        condition: service_healthy

  redis:
    container_name: rs
    image: redis:7.2.2
    env_file:
      - dev.env
    ports:
      - '6379:6379'
    hostname: localhost
